#!/usr/bin/env python2
import os,sys,re,string
import zipfile

printable = set(string.printable)

def process(stream):
    found_str = ""
    while True:
        data = stream.read(1024*4)
        if not data:
            break
        for char in data:
            if char in printable:
                found_str += char
            elif len(found_str) >= 4:
                yield found_str
                found_str = ""
            else:
                found_str = ""

def make_thumb(src, out, size):
    global logger
    apk = zipfile.ZipFile(src)
    with open(src) as fd:
        for found_str in process(fd):
            result=re.match(r'(res\/.*ic_launcher.png)', found_str)
            if result:
                break
    
    fd = open(out, "w")
    fd.write(apk.read(found_str))
    fd.close()
    
    pass


def main(argv):
    i = 0;
    global logger
    
    # initial variables
    source = ""
    size = ""
    output = ""

    for arg in argv:
        if i == 1:
            source = argv[i]
        elif i == 2:
            output = argv[i]
        elif i == 3:
            size = argv[i]
        
        i += 1
    
    make_thumb(source, output, size)
    pass

if __name__ == '__main__':
    sys.exit(main(sys.argv))
